### ISSUE TITLE
分割符是；的问题

### ISSUE THREAD

**Issue by jtyoui** [szyhf/go-excel#10]
`Slice   []int xlsx:"split(|)"`  如果分隔符不是 `|`而是`;`，代码将无效

**Comment by szyhf** [comment]
因为;被作为多个参数的分隔符，有需要使用;的话，需要使用扩展接口：

```go
type ExcelFiledConfiger interface {
	GetXLSXFieldConfigs() map[string]FieldConfig
}
```

可以参考`field_config_test.go`里的用法。
