### ISSUE TITLE
相同标题会error

### ISSUE THREAD

**Issue by huizhang001** [szyhf/go-excel#12]
### 问题描述：
1. xxx.xlsx 文件格式
<img width="476" alt="image" src="https://user-images.githubusercontent.com/26496638/190995335-1202a5e0-c5fd-48d7-9f61-3e0e642291bc.png">
2. 代码 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/26496638/190997039-9c3695b6-d5f6-48c8-b365-ef9d73ae52d2.png">
3. 报错信息
`title row has duplicated key and can not read into a map or struct`

### 诉求：
1. 提供 struct 时候 只需要严格按照 struct 字段定义去解析就行 
2. 缺少字段可以设置默认值或者 error 也可以
3.  相同标题时，让用户自己决定是不是返回error
4. 相同标题时，可以制定覆盖策略，比如前面覆盖后面，后面覆盖前面等

谢谢谢！！！

**Comment by szyhf** [comment]
嗯，需求很合理，不过按目前的设计方案，实现不了，抱歉啦
