### ISSUE TITLE
GetXLSXSheetName这个方法怎么调用的，我不太理解

### ISSUE THREAD

**Issue by liuzi-long901** [szyhf/go-excel#13]
GetXLSXSheetName 获取excel sheet 名称

**Comment by szyhf** [comment]
这是一个回调方法……不是给你调用的，是你实现了以后，给库调用的，用于某些复杂场景下可以动态返回自定义的SheetName。

---

如果你想获得Sheet的列表，用`Connecter`的`GetSheetNames() []string`方法。

**Comment by liuzi-long901** [comment]
直接实现吗



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Back ***@***.***> |
| 日期 | 2022年09月23日 18:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [szyhf/go-excel] GetXLSXSheetName这个方法怎么调用的，我不太理解 (Issue #13) |

这是一个回调方法……不是给你调用的，是你实现了以后，给库调用的，用于某些复杂场景下可以动态返回自定义的SheetName。

如果你想获得Sheet的列表，用Connecter的GetSheetNames() []string方法。

**Comment by szyhf** [comment]
如果你不理解这个是做什么的，说明你不需要处理这个场景，忽略即可……

**Comment by liuzi-long901** [comment]
哈哈哈我觉得另一个star多的不好用所以用的这个



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Back ***@***.***> |
| 日期 | 2022年09月23日 18:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [szyhf/go-excel] GetXLSXSheetName这个方法怎么调用的，我不太理解 (Issue #13) |

如果你不理解这个是做什么的，说明你不需要处理这个场景，忽略即可……

**Comment by szyhf** [comment]
是的，我这个就是砍了大部分定制化功能，给特定场景用的，约束会比较多，可以参考readme里边的说明。
