### ISSUE TITLE
Can we have a New Method in interface<Reader>?

### ISSUE THREAD

**Issue by wotmshuaisi** [szyhf/go-excel#2]
requesting a new Method in interface <Reader> that can allow us to get Raw data

```go
// Reader to read excel
type Reader interface {
	// RawRow return current row data
        RawRow() ([]string, error)
}
```

**Comment by szyhf** [comment]
Good idea

**Comment by wotmshuaisi** [comment]
#3

**Comment by szyhf** [comment]
Really thanks for your PR, but considering compatibility I have implement it in a different way.

Hope you enjoy it~

**Comment by szyhf** [comment]
Ref: https://godoc.org/github.com/szyhf/go-excel#example-Reader--ReadSlice
