### ISSUE TITLE
Is there a way to read sub column ?

### ISSUE THREAD

**Issue by weeee9** [szyhf/go-excel#4]
I got a excel file to read, and it has a columns look like this:

![Imgur](https://i.imgur.com/fsO9Ftx.png)

I want to read sub column a's and b's value ( both are 0.11)

Is there a way to do things like this ?

**Comment by szyhf** [comment]
Err, if you want to get a list of struct like 

```go
type something struct{
    A float64
    B float64
}
```
you can try set the `config.TitleRowIndex` to  1

**Comment by weeee9** [comment]
@szyhf sorry for not made myself clear

What I mean is let's say I have sheet like this:

![example](https://user-images.githubusercontent.com/12977581/71664720-fd854200-2d94-11ea-8a17-b82c6ac2ee19.JPG)

and I have structures like:
```go
type excel struct {
    A    string     `xlsx:"A"`
    B    string     `xlsx:"B"`
    C    string     `xlsx:"C"`
    D    subD       `xlsx:"D"`
}

type subD struct {
    D1    int
    D2    int
}
```
or just

```go
type excel struct {
    A      string     `xlsx:"A"`
    B      string     `xlsx:"B"`
    C      string     `xlsx:"C"`
    D1    int         `xlsx:"D1"`
    D2    int         `xlsx:"D2"`
}
```

I currently can't find a way to read excel to struct like this, is it possible do such thing?

**Comment by szyhf** [comment]
Sorry, the scheme of sub columns has some complex situation, may be you can consider using `github.com/360EntSecGroup-Skylar/excelize` instead ?

**Comment by weeee9** [comment]
@szyhf I'll try `excelize`, thanks for the help.

**Comment by szyhf** [comment]
@weeee9 
There might be some cheat for your example.

The library used to support binding to the default column name in exce like 'A', 'B', 'C', 'D' ......, 'XFC', 'XFD' can be used as column name by 26-number-system.

But in that cases, it's easy to confuse with the real column name. So I disable the feature.

You may fork the library and fix the code blow:

https://github.com/szyhf/go-excel/blob/4001b412307186a4cb13d0151ef3e1bbe7a2eb29/title.go#L89-L90

to :

```golang
cloIndex = twentysix.ToDecimalism(field.ColumnName)
// return nil, fmt.Errorf("go-excel: column name = \"%s\" is not exist", field.ColumnName)
```

than you can set a struct and config like : 

```golang
type excel struct {
    A      string     `xlsx:"column(A)"`
    B      string     `xlsx:"column(B)"`
    C      string     `xlsx:"column(C)"`
    D1    int         `xlsx:"column(D)"`
    D2    int         `xlsx:"column(E)"`
}

        rd, err := conn.NewReaderByConfig(&excel.Config{
		// Sheet name as string or sheet model as object or as slice of objecg.
		Sheet: "xxx",
		// Ignore titles
		TitleRowIndex: 0,
		// Skip the first two row including the sub columns
		Skip: 2,
		// Auto prefix to sheet name.
		Prefix: "",
		// Auto suffix to sheet name.
		Suffix: advSheetSuffix,
	})
```

I was considering to add a new tag to support it ....
