### ISSUE TITLE
Columns with header names including "(" or ")" are not read.

### ISSUE THREAD

**Issue by leapforce-nl** [szyhf/go-excel#6]
Hi, 
I have an Excel sheet with column names like "Patiënten (in aantallen)". These columns are not read, probably due to the "(" and ")". Can you maybe fix this? Thanks in advance! And thanks for the repository.

Kind regards, Michiel

**Comment by leapforce-nl** [comment]
I fixed this locally by changing 1 line in schema.go/getTagParam to:

end := strings.LastIndex(v, ")")

**Comment by szyhf** [comment]
It’s a bit cumbersome to deal with escape characters, I think is better to add a new optional interface to allows you define each schema by yourself

**Comment by szyhf** [comment]
Consider use the new interface in 8c6a0e7

**Comment by chaoyueziji** [comment]
我好像又遇到了类似的问题，"Patiënten (in aantallen)" 这样是无法解析的，但是 "Patiënten (in aantallen) *" 又可以解析

**Comment by szyhf** [comment]
> 我好像又遇到了类似的问题，"Patiënten (in aantallen)" 这样是无法解析的，但是 "Patiënten (in aantallen) *" 又可以解析

使用`FieldConfig`，直接填原始字符串，要不文本解析这块的特殊情况太多了，不好弄
