### ISSUE TITLE
新版本读取xlsx报错

### ISSUE THREAD

**Issue by sunzhaopeng** [szyhf/go-excel#8]
panic: title row has duplicated key and can not read into a map or struct

使用v1.4.3版本可以正常读取，使用最新的v1.5.1版本读取就出现上面的error，麻烦帮忙看一下

**Comment by szyhf** [comment]
这种问题你得上传原始的excel……我才能看

而且报错原因写的不是很清楚了么？存在多于两列的title是一样的……

**Comment by sunzhaopeng** [comment]
> 这种问题你得上传原始的excel……我才能看
> 
> 另外，报错原因是存在多于两列的title是一样的。
> 
> 之前的版本之所以能读取是因为有bug，会随机读取一列，所以才加了前置检测。

[property_level_up.xlsx](https://github.com/szyhf/go-excel/files/6395916/property_level_up.xlsx)

需要读取的excel我已经上传，excel的每个sheet应该都是没有重复的列的，麻烦大佬给看一眼，谢谢

**Comment by szyhf** [comment]
第G H I列存在空白数据，应该是之前曾经有数据，后来删了，但删除是把数据清空（你可以理解为，数据存储了一个空字符串）

然后把三列的空字符串，视作titile相同。

目前这个东西暂时在库里没法兼容，修复excel文件的话，选中整一列，右键点删除列即可。

**Comment by sunzhaopeng** [comment]
了解，多谢大佬！

**Comment by szyhf** [comment]
不客气哈
