### ISSUE TITLE
can we use column name as title? 

### ISSUE THREAD

**Issue by armenpn** [szyhf/go-excel#9]
can we use column names, such as A, B, AB, for some excel doesn't contain any title or the title may be updated from day to day by uploader. 
such as can we define structs like:

```go
type Demo struct {
	ID  string `xlsx:"A"`
	Sku string `xlsx:"B"`
}
```

found this:
If no title row privoded, the default column name in exce like 'A', 'B', 'C', 'D' ......, 'XFC', 'XFD' can be used as column name by 26-number-system.

what value should pass to TitleRowIndex

**Comment by szyhf** [comment]
At the earliest version, it can work like that, but some bug was cased and I comment the feature, let me see what happened.
